# async 函数

async 函数是一种基于 Promise 的语法糖，用于简化异步操作的编码和处理。

async 函数会自动将函数体包装成一个 Promise 对象，这个 Promise 对象的 resolve 值即为函数返回值，reject 值为抛出的错误信息。

<br>

## async 函数的返回值

1. 如果 async 函数返回 Promise 对象：

```js
async function show() {
    return Promise.resolve('ok'); // 返回 Promise 对象
}
const p1 = show();

// 同步获取
console.log('p1', p1); // p1 Promise { <pending> }

// 异步获取 (宏任务)
setTimeout(() => {
    console.log('p1', p1); // p1 Promise {<fulfilled>: 'ok'}
}, 0);

// 异步获取 (微任务)
p1.then(val => {
    console.log('val', val); // val ok
});
```

输出顺序：`p1 Promise { <pending> }` → `val ok` → `p1 Promise {<fulfilled>: 'ok'}`

2. 如果 async 函数返回任意非 Promise 对象的数据：

```js
async function show() {
    return 'ok'; // 返回任意非 Promise 对象的数据
}
const p1 = show();

// 同步获取
console.log('p1', p1); // p1 Promise {<fulfilled>: 'ok'}

// 异步获取
p1.then(val => {
    console.log('val', val); // val ok
});
```

3. 如果 async 函数内抛出了异常，将得到 rejected 的 Promise 实例，该 Promise 实例的值为抛出的异常信息

```js
async function show() {
    throw '出错了';
}
const p1 = show();

// 同步获取
console.log('p1', p1); // p1 Promise {<rejected>: '出错了'}

// 异步获取
p1.catch(reason => {
    console.log('reason', reason); // reason 出错了
});
```

<br>

## async 函数的 4 种写法

```js
async function fun1() {} // 普通函数

const fun2 = async function () {}; // 函数表达式

const fun3 = async () => {}; // 箭头函数

const obj = {
    name: 'superman',
    async showName() {}, // 对象方法
};
```

<br><br>

# await 关键字

我们可以在 async 函数的**直接子作用域**中，使用 `await` 关键字来控制异步操作的执行。

当 await 关键字与一个 Promise 对象一起使用时，它会暂停 async 函数的执行，直到这个 Promise 对象的状态变成 resolve 或 reject。

一旦 Promise 对象的状态变为 resolve，await 关键字将会返回该 Promise 对象的 resolve 值。如果 Promise 对象的状态变为 reject，则 await 关键字将会抛出相应的错误信息。

`await` 关键字后面的代码对应 Promise 执行器中的代码，会同步执行；
`await` 下一行开始的代码对应 `then` 方法中的代码，属于异步操作。

```js
async function test() {
    console.log('async');

    const val1 = await new Promise(resolve => {
        setTimeout(() => {
            resolve('ProResolve');
        }, 1000);
    });
    console.log(val1);

    const val2 = await '普通数据';
    console.log(val2);
}

console.log('before async');
test();
console.log('after async');
```

上例的打印顺序为：`before async` - `async` - `after async` - `ProResolve` - `普通数据`

上例等效于：

```js
function test() {
    new Promise(resolve => {
        console.log('async');
        setTimeout(() => {
            resolve('ProResolve');
        }, 1000);
    })
        .then(val1 => {
            console.log(val1);
            return '普通数据';
        })
        .then(val2 => console.log(val2));
}

console.log('before await');
test();
console.log('after await');
```

-   如果 `await` 右侧的是 rejected 状态的 Promise 实例，就会抛出异常：

```js
async function show() {
    let res = await Promise.reject('wrong'); // 这里抛出错误，后面的语句都不会执行
    console.log('res', res); // 这里不会打印
}
show();
```

可以使用 Promise 实例调用 catch 方法处理错误：

```js
async function show() {
    const res = await Promise.reject('wrong').catch(reason => {
        return reason;
    });
    console.log('res', res); // res wrong
}
show();
```

也可以通过 `try … catch` 语句捕获并处理错误：

```js
async function show() {
    try {
        const res = await Promise.reject('wrong');
        console.log('res', res); // 这里不会打印
    } catch (error) {
        console.log('error', error); // error wrong
    }
}
show();
```

<br><br>

# await 使用陷阱

1. 对于并行执行的异步任务，其实并不适合用 await 修饰

```js
async function fun() {
    const pro1 = await fetch('url1');
    const pro2 = await fetch('url2');
    // ...
}
```

上例这样写，虽没有错误，但会打破两个 fetch 的并行，这需要等待第 1 个异步任务执行完毕之后，才会执行第 2 个异步任务
所以我们可以不用 await 修饰这些并行执行的异步操作

```js
async function fun() {
    const proA = fetch('url1'); // 只要不加 await，Ajax 就会同时请求
    const proB = fetch('url2');
    const pro1 = await proA;
    const pro2 = await proB;
    console.log(pro1, pro2);
    // ...
}
```

这里更高效的做法：通过 `Promise.all` 组合起来

```js
async function fun() {
    const proA = fetch('url1'); // 只要不加 await，Ajax 就会同时请求
    const proB = fetch('url2');
    const [pro1, pro2] = await Promise.all([proA, proB]);
    // ...
}
```

2. 如果我们需要在循环中执行异步操作，是不能够直接调用 `forEach` / `map` 这一类方法的。
   即使我们在回调函数中写了 `await`，`forEach` 也会立刻返回，并不会暂停等到所有异步操作都执行完毕

```js
async function fun() {
    [1, 2, 3].forEach(async i => {
        await someAsyncOperation();
    });
    console.log('done');
}
fun();
```

如果我们希望等待循环中的异步操作都完成之后才继续执行，那我们还是应该使用传统的 `for` 循环

```js
async function fun() {
    for (const i of [1, 2, 3]) {
        await someAsyncOperation();
    }
    console.log('done');
}
fun();
```

更进一步，如果我们想所有操作都并发执行，可以使用 `for await`：
这里的 `for` 循环依然会等到所有的异步操作都完成之后才继续向后执行

```js
async function fun() {
    let pros = [
        someAsyncOperation(),
        someAsyncOperation(),
        someAsyncOperation(),
    ];
    for await (let result of pros) {
        // ...
    }
    console.log('done');
}
fun();
```

<br><br>

# 案例

使用回调函数读取多个文件

```js
const fs = require('fs');

fs.readFile('./demo.html', (err, data1) => {
    if (err) throw err;
    fs.readFile('./demo.html', (err, data2) => {
        if (err) throw err;
        fs.readFile('./demo.html', (err, data3) => {
            if (err) throw err;
            console.log(data1 + data2 + data3);
        });
    });
});
```

使用 `async` & `await` 读取多个文件

```js
const fs = require('fs');
const util = require('util');

// 把 fs.readFile 方法封装成 Promise 实例
let myReadFile = util.promisify(fs.readFile);

async function main() {
    try {
        let data1 = await myReadFile('./demo.html');
        let data2 = await myReadFile('./demo.html');
        let data3 = await myReadFile('./demo.html');
        console.log(data1 + data2 + data3);
    } catch (error) {
        console.log(error);
    }
}

main();
```
